select
    am.merge_column
    ,case am.message_type
        when 1 then '系统发送'
        when 2 then '手动操作发送'
    end 数据来源
    ,case am.`punish_category`
        When 1 then '虚假问题件/虚假留仓件'
        When 2 then '5天以内未妥投，且超24小时未更新'
        When 3 then '5天以上未妥投/未中转，且超24小时未更新'
        When 4 then '对问题件解决不及时'
        When 5 then '包裹配送时间超三天'
        When 6 then '未在客户要求的改约时间之前派送包裹'
        When 7 then '包裹丢失'
        When 8 then '包裹破损'
        When 9 then '其他'
        When 10 then '揽件时称量包裹不准确'
        When 11 then '出纳回款不及时'
        When 12 then '迟到罚款 每分钟10泰铢'
        When 13 then '揽收或中转包裹未及时发出'
        When 14 then '仓管对工单处理不及时'
        When 15 then '仓管未及时处理问题件包裹'
        When 16 then '客户投诉罚款 已废弃'
        When 17 then '故意不接公司电话 自定义'
        When 18 then '仓管未交接SPEED/优先包裹给快递员'
        When 19 then 'PRI或者speed包裹未妥投'
        When 20 then '虚假妥投'
        When 21 then '客户投诉'
        When 22 then '快递员公款超时未上缴'
        When 23 then 'miniCS工单处理不及时'
        When 24 then '客户投诉-虚假问题件/虚假留仓件'
        When 25 then '揽收禁运包裹'
        When 26 then '早退罚款'
        When 27 then '班车发车晚点'
        When 28 then '虚假回复工单'
        When 29 then '未妥投包裹没有标记'
        When 30 then '未妥投包裹没有入仓'
        When 31 then 'SPEED/PRI件派送中未及时联系客户'
        When 32 then '仓管未及时交接SPEED/PRI优先包裹'
        When 33 then '揽收不及时'
        When 34 then '网点应盘点包裹未清零'
        When 35 then '漏揽收'
        When 36 then '包裹外包装不合格'
        When 37 then '超大件'
        When 38 then '多面单'
        When 39 then '不称重包裹未入仓'
        When 40 then '上传虚假照片'
        When 41 then '网点到件漏扫描'
        When 42 then '虚假撤销'
        When 43 then '虚假揽件标记'
        When 44 then '外协员工日交接不满50件包裹'
        When 45 then '超大集包处罚'
        When 46 then '不集包'
        When 47 then '理赔处理不及时'
        When 48 then '面单粘贴不规范'
        When 49 then '未换单'
        When 50 then '集包标签不规范'
        When 51 then '未及时关闭揽件任务'
        When 52 then '虚假上报（虚假违规件上报）'
        When 53 then '虚假错分'
        When 54 then '物品类型错误（水果件）'
        When 55 then '虚假上报车辆里程'
        When 56 then '物品类型错误（文件）'
        When 57 then '旷工罚款'
        When 58 then '虚假取消揽件任务'
        When 59 then '72h未联系客户道歉'
        When 60 then '虚假标记拒收'
        When 61 then '外协投诉主管未及时道歉'
        When 62 then '外协投诉客户不接受道歉'
        When 63 then '揽派件照片不合格'
        When 64 then '揽件任务未及时分配'
        When 65 then '网点未及时上传回款凭证'
        When 66 then '网点上传虚假回款凭证'
        when 67 then '时效延迟'
        when 68 then '未及时呼叫快递员'
        when 69 then '未及时尝试派送'
        when 70 then '退件包裹未处理'
        when 71 then '不更新包裹状态'
        when 72 then 'PRI包裹未及时妥投'
        when 73 then '临近时效包裹未及时妥投'
        when 74 then '暴力分拣'
        when 75 then '上报拒收证据不合格'
        when 76 then '个人代理-不接单未提前通知'
        when 77 then '个人代理-终止合同未提前通知'
        when 78 then '待退件包裹未及时发出'
        when 79 then '工作严重低效'
        when 80 then 'EPOD拍照不合格'
        when 81 then '虚假标记改约'
        when 82 then '虚假标记错分'
        when 83 then '虚假标记联系不上收件人'
        when 84 then '24小时未更新有效路由'
        when 85 then '72小时未终态'
        when 86 then '尝试揽收及时率不达标 '
        when 87 then '揽收未及时发出'
        when 88 then '退件率不达标'
        when 89 then '承包加盟商-未提供服务'
        when 90 then '照片不合格'
    end as '处罚原因'
    ,case am.`punish_sub_category`
        when 1 then '超大件'
        when 2 then '违禁品'
        when 3 then '寄件人电话号码是空号'
        when 4 then '收件人电话号码是空号'
        when 5 then '虛假上报车里程模糊'
        when 6 then '虛假上报车里程'
        when 7 then '重量差（复秤-揽收）（0.5kg,2kg]'
        when 8 then '重量差（复秤-揽收）（2kg,5kg]'
        when 9 then '重量差（复秤-揽收）>5kg'
        when 10 then '重量差（复秤-揽收）<-0.5kg'
        when 11 then '重量差（复秤-揽收）（1kg,3kg]'
        when 12 then '重量差（复秤-揽收）（3kg,6kg]'
        when 13 then '重量差（复秤-揽收）>6kg'
        when 14 then '重量差（复秤-揽收）<-1kg'
        when 15 then '尺寸差（复秤-揽收）(10cm,20cm]'
        when 16 then '尺寸差（复秤-揽收）(20cm,30cm]'
        when 17 then '尺寸差（复秤-揽收）>30cm'
        when 18 then '尺寸差（复秤-揽收）<-10cm'
        when 22 then '虛假上报车里程 虚假-图片与数字不符合'
        when 23 then '虛假上报车里程 虚假-滥用油卡'
        when 24 then '虚假标记拒收'
        when 25 then '虚假标记改约时间'
        when 26 then '恢复任务再次取消'
        when 27 then '个人外协违规投诉主管72小时内未道歉'
        when 28 then '个人外协违规投诉客户不接受主管道歉'
        when 29 then '虛假上报车里程 虚假审批里程'

        when 71 then  '重量差（复秤后-复秤前）【KG】（2kg,5kg]'
        when 72 then   '重量差（复秤后-复秤前）【KG】 >5 kg'
        when 73 then   '重量差（复秤后-复秤前）【KG】<-2kg'
        when 74 then   '尺寸差（复秤后-复秤前）【CM】(20,30]'
        when 75 then   '尺寸差（复秤后-复秤前）【CM】>30'
        when 76 then   '尺寸差（复秤后-复秤前）【CM】<-20'
        else am.punish_category
    end as '具体原因'
    ,am.punish_money 处罚金额
    ,am.staff_info_id 惩罚人员ID
    ,hjt.job_name 员工职位
    ,case
        when hsi.`state`=1 and hsi.`wait_leave_state`=0 then '在职'
        when hsi.`state`=1 and hsi.`wait_leave_state`=1 then '待离职'
        when hsi.`state`=2 then '离职'
        when hsi.`state`=3 then '停职'
    end as 在职状态
    ,dm.store_name 责任网点名称
    ,dm.region_name 大区
    ,dm.piece_name 片区
    ,am.abnormal_time 异常日期
    ,dm.store_type 网点类型
    ,case am.abnormal_object
        when 0 then '个人罚款'
        when 1 then '集体罚款'
        when 2 then '加盟商罚款'
    end  处罚类型
    ,case
        when hsi.hire_type in (1,2,3,4,5) then '正式员工'
        when hsi.hire_type in (11,12) then '外协'
        when hsi.hire_type in (13) then '个人代理'
        when hsi.hire_type in (14) then '兼职代理'
    end 员工类型
    ,case
        when am.isappeal = 1 then '未申诉'
        when am.isappeal = 2 then '申诉中'
        when am.isappeal = 3 then '保持原判'
        when am.isappeal = 4 then '已变更'
        when am.isappeal = 5 or am.isdel = 1 then '已删除'
    end 状态
#     count(1)
from my_bi.abnormal_message am
left join my_bi.hr_staff_info hsi on hsi.staff_info_id = am.staff_info_id
left join my_bi.hr_job_title hjt on hjt.id = hsi.job_title
left join dwm.dim_my_sys_store_rd dm on dm.store_id = am.store_id and dm.stat_date = date_sub(curdate(), 1)
where
    am.abnormal_time >= '2024-10-11'
    and am.abnormal_time < '2024-10-21'