
select
	 di.pno '运单号'
     ,dd.client_name 客户名称
	 ,convert_tz(pi.created_at,'+00:00','+08:00') '揽收日期'
	 ,ss.name '揽收网点'
	 ,case pi.state
		  when 1 then '已揽收'
		  when 2 then '运输中'
		  when 3 then '派送中'
		  when 4 then '已滞留'
		  when 5 then '已签收'
		  when 6 then '疑难件处理中'
		  when 7 then '已退件'
		  when 8 then '异常关闭'
		  when 9 then '已撤销'
		  ELSE pi.state
		  end as '包裹状态'
	 ,ss1.name '目的地网点'
	 ,ss2.name '上报疑难件网点'
	, di.diff_marker_category
    ,case di.diff_marker_category # 疑难原因
            when 1 then '客户不在家/电话无人接听'
            when 2 then '收件人拒收'
            when 3 then '快件分错网点'
            when 4 then '外包装破损'
            when 5 then '货物破损'
            when 6 then '货物短少'
            when 7 then '货物丢失'
            when 8 then '电话联系不上'
            when 9 then '客户改约时间'
            when 10 then '客户不在'
            when 11 then '客户取消任务'
            when 12 then '无人签收'
            when 13 then '客户周末或假期不收货'
            when 14 then '客户改约时间'
            when 15 then '当日运力不足，无法派送'
            when 16 then '联系不上收件人'
            when 17 then '收件人拒收'
            when 18 then '快件分错网点'
            when 19 then '外包装破损'
            when 20 then '货物破损'
            when 21 then '货物短少'
            when 22 then '货物丢失'
            when 23 then '详细地址错误'
            when 24 then '收件地址已废弃或不存在'
            when 25 then '收件人电话号码错误'
            when 26 then 'cod金额不正确'
            when 27 then '无实际包裹'
            when 28 then '已妥投未交接'
            when 29 then '收件人电话号码是空号'
            when 30 then '送错网点'
            when 31 then '省市乡邮编错误'
            when 32 then '禁运品'
            when 33 then '严重破损（丢弃）'
            when 34 then '退件两次尝试派送失败'
            when 35 then '不能打开locker'
            when 36 then 'locker不能使用'
            when 37 then '该地址找不到lockerstation'
            when 38 then '一票多件'
            when 39 then '多次尝试派件失败'
            when 40 then '客户不在家/电话无人接听'
            when 41 then '错过班车时间'
            when 42 then '目的地是偏远地区,留仓待次日派送'
            when 43 then '目的地是岛屿,留仓待次日派送'
            when 44 then '企业/机构当天已下班'
            when 45 then '子母件包裹未全部到达网点'
            when 46 then '不可抗力原因留仓(台风)'
            when 47 then '虚假包裹'
            when 50 then '客户取消寄件'
            when 51 then '信息录入错误'
            when 52 then '客户取消寄件'
            when 53 then 'lazada仓库拒收'
            when 69 then '禁运品'
            when 70 then '客户改约时间'
            when 71 then '当日运力不足，无法派送'
            when 72 then '客户周末或假期不收货'
            when 73 then '详细地址错误'
            when 74 then '收件地址已废弃或不存在'
            when 75 then '收件人电话号码错误'
            when 76 then 'cod金额不正确'
            when 77 then '企业/机构当天已下班'
            when 78 then '收件人电话号码是空号'
            when 79 then '快件分错网点-地址错误'
            when 80 then '客户取消任务'
            when 81 then '重复下单'
            when 82 then '已完成揽件'
            when 83 then '联系不上客户'
            when 84 then '包裹不符合揽收条件（超大件、违禁物品）'
            when 85 then '寄件人电话号码是空号'
            when 86 then '包裹不符合揽收条件超大件'
            when 87 then '包裹不符合揽收条件违禁品'
            when 88 then '寄件人地址为岛屿'
            when 89 then '运力短缺，跟客户协商推迟揽收'
            when 90 then '包裹未准备好推迟揽收'
            when 91 then '包裹包装不符合运输标准'
            when 92 then '客户提供的清单里没有此包裹'
            when 93 then '包裹不符合揽收条件（超大件、违禁物品）'
            when 94 then '客户取消寄件/客户实际不想寄此包裹'
            when 95 then '车辆/人力短缺推迟揽收'
            when 96 then '遗漏揽收(已停用)'
            when 97 then '子母件(一个单号多个包裹)'
            when 98 then '地址错误addresserror'
            when 99 then '包裹不符合揽收条件：超大件'
            when 100 then '包裹不符合揽收条件：违禁品'
            when 101 then '包裹包装不符合运输标准'
            when 102 then '包裹未准备好'
            when 103 then '运力短缺，跟客户协商推迟揽收'
            when 104 then '子母件(一个单号多个包裹)'
            when 105 then '破损包裹'
            when 106 then '空包裹'
            when 107 then '不能打开locker(密码错误)'
            when 108 then 'locker不能使用'
            when 109 then 'locker找不到'
            when 110 then '运单号与实际包裹的单号不一致'
            when 111 then 'box客户取消任务'
            when 112 then '不能打开locker(密码错误)'
            when 113 then 'locker不能使用'
            when 114 then 'locker找不到'
            when 115 then '实际重量尺寸大于客户下单的重量尺寸'
            when 116 then '客户仓库关闭'
            when 117 then '客户仓库关闭'
            when 118 then 'SHOPEE订单系统自动关闭'
            when 119 then '客户取消包裹'
            when 121 then '地址错误'
            when 122 then '当日运力不足，无法揽收'
        end  as ' 疑难件原因 '
	 ,convert_tz(di.created_at,'+00:00','+08:00') '上报时间'
     ,date(convert_tz(di.created_at,'+00:00','+08:00')) '上报日期'
	 ,di.staff_info_id '上报人'
	 ,hi.name '上报人姓名'
	 ,sd.name '处理机构'
	 ,cdt.operator_id '客服操作人ID'
	 ,convert_tz(cdt.first_operated_at,'+00:00','+08:00') '第一次处理时间'
	 ,ifnull(convert_tz(cdt.last_operated_at,'+00:00','+08:00'),convert_tz(cdt.first_operated_at,'+00:00','+08:00')) '最后一次处理时间'
	 ,case cdt.state
		  when 0 then '未处理'
		  when 1 then '已处理'
		  when 2 then '正在沟通中'
		  when 3 then '财务驳回'
		  when 4 then '客户未处理'
		  when 5 then '转交闪速系统'
		  when 6 then '转交QAQC'
		  else cdt.state
		  end '客服处理情况'

     ,case cdt.negotiation_result_category
          when 1 then '赔偿'
          when 2        then '关闭订单(不赔偿不退货)'
          when 3        then'退货'
          when 4        then '退货并赔偿'
          when 5        then '继续配送'
          when 6        then '继续配送并赔偿'
          when 7        then '正在沟通中'
          when 8        then '丢弃包裹的，换单后寄回BKK'
          when 9        then '货物找回，继续派送'
          when 10       then  '改包裹状态'
          when 11       then '需客户修改信息'
          when 12       then '丢弃并赔偿（包裹发到内部拍卖仓）'
	  end '处理结果'
	 ,datediff('hour',convert_tz(di.created_at,'+00:00','+08:00'),ifnull(convert_tz(cdt.last_operated_at,'+00:00','+08:00'),convert_tz(cdt.first_operated_at,'+00:00','+08:00'))) '客服处理-上报时长/h'
	 ,case di.state
		  when 0 then '未处理'
		  when 1 then '已处理'
		  else di.state
      end '疑难件处理情况'
	 ,if(di.state=1,convert_tz(cdt.updated_at,'+00:00','+08:00'),null)  '疑难件处理完成时间'
# 	 ,datediff('hour',convert_tz(di.created_at,'+00:00','+08:00'),if(di.state=1,convert_tz(di.updated_at,'+00:00','+08:00'),null)) '疑难件处理时长/h'
# 	 ,datediff(now(),if(di.state=0,convert_tz(di.created_at,'+00:00','+08:00'),null) ) '未处理当前时间-上报时间/d'
#     ,if(di.state = 0 and di.created_at >= concat(curdate(), ' 12:00:00'), '当日20点后', '之前') 8点判断
    ,case
        when di.created_at >= date_add('${date1}', interval 12 hour ) then '当日20点后'
        when di.created_at < date_add('${date1}', interval 12 hour ) and di.created_at >= date_sub('${date1}', interval 8 hour ) then '积压时间 0 day'
        when di.created_at < date_sub('${date1}', interval 8 hour ) then concat('积压时间', datediff('${date1}', convert_tz(di.created_at , '+00:00', '+08:00'), ' day'))
    end 积压时长
    ,case
        when cdt.state = 1 and cdt.updated_at <= date_add(cdt.created_at, interval  2 hour) then '及时'
        when cdt.state = 1 and cdt.updated_at > date_add(cdt.created_at, interval  2 hour) then '不及时'
        else null
    end 是否及时
    ,if(di.state = 1 , round(timestampdiff(second, di.created_at, di.updated_at )/ 3600, 2), null) 处理时长_h
from ph_staging.diff_info di
# left join dwm.dwd_dim_dict tdt2 on di.diff_marker_category= tdt2.element and tdt2.db = 'ph_staging' and tdt2.tablename = 'diff_info' and tdt2.fieldname = 'diff_marker_category' -- 标记原因
join ph_staging.parcel_info pi on pi.pno=di.pno
join dwm.dwd_dim_bigClient dd on pi.client_id=dd.client_id
left join ph_bi.sys_store ss on ss.id=pi.ticket_pickup_store_id #揽收网点
left join ph_bi.sys_store ss1 on ss1.id=pi.dst_store_id#目的地网点
left join ph_bi.sys_store ss2 on ss2.id=di.store_id #上报当前网点
left join ph_bi.hr_staff_info hi on hi.staff_info_id=di.staff_info_id #疑难件处理人对应网点
join ph_staging.customer_diff_ticket cdt on cdt.diff_info_id=di.id and cdt.organization_type=2 #疑难件处理进度
left join ph_bi.hr_staff_info hi2 on hi2.staff_info_id=cdt.operator_id #疑难件处理人对应网点
left join ph_bi.sys_department sd on sd.id=hi2.node_department_id
where
    di.diff_marker_category in (23,73,29,78,25,75,31,79)
    and di.created_at >= date_add('${date1}', interval  1 hour)
    and di.created_at < date_add('${date1}', interval 12 hour)